apiVersion: v1
kind: Pod
metadata:
  name: hello-app
  labels:
    app.kubernetes.io/name: hello-app
spec:
  containers:
    - name: hello-service
      image: {username}/multiple-entry-points:local # This is the Java API image with the second entry point.
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 8080